spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student-diary
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/
app:
  storage:
    location: C:/diary/